shop/goods/urls.py
from django.urls import path

from .views import shoes, index, shoescart, view_cart, update_cart, remove_item_from_cart, display_info, order, popular, newest, delivery, sale, clothes, clothcart, money, money_back, accessories, accessory

app_name = 'goods'

urlpatterns = [
    path('', index, name='index'),

    path('shoes/', shoes, name='shoes'),
    path('clothes/', clothes, name='clothes'),
    path('accessories/', accessories, name='accessories'),

    path('shoes/<int:product_id>/', shoescart, name="shoe"),
    path('clothes/<int:product_id>/', clothcart, name="cloth"),
    path('accessories/<int:product_id>/', accessory, name='accessory'),

    path('shoes/add_to_cart/<int:product_id>/', shoescart, name='add_to_cart'),
    path('clothes/add_to_cart/<int:product_id>/', clothcart, name='clothes_add_to_cart'),
    path('accessories/add_to_cart/<int:product_id>/', accessory, name='accessory_add_to_cart'),

    path('view_cart/', view_cart, name='view_cart'),
    path('update_cart/', update_cart, name='update_cart'),
    path('remove_item_from_cart/', remove_item_from_cart, name='remove_item_from_cart'),
    path('order/', order, name='order'),

    path('popular/', popular, name='popular'),
    path('new/', newest, name='new'),
    path('sale/', sale, name='sale'),

    path('faq/', display_info, name='faq'),
    path('delivery/', delivery, name='delivery'),
    path('payment/', money, name='payment'),
    path('return-info/', money_back, name='return')

]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from shop import settings

urlpatterns = [
    path('', include('goods.urls', namespace='goods')),
    path('admin/', admin.site.urls),
]



if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/templates/catalog/accesories.html
{% extends "base.html" %}
{% load static %}

{% block main %}
<div class="banners">
    {% for banner in banners %}
    <div class="banner">
        <a href="{{banner.url}}">
            <img src="{{banner.image.url}}" alt="">
        </a>
    </div>
    {% endfor %}
</div>
<div class="list_goods">
    <div class='fltrs'>
        <div class="filter-toggle">ФИЛЬТРЫ</div>
        <div class="filter-area">
            <form method="GET" action="{% url 'goods:accessories' %}">
                <div class='filter-srch'>
                    <input type="text" name="search_query" placeholder="Поиск по названию..." value="{{ request.GET.search_query }}">
                </div>
                <div class='filter-price'>
                    <input type="number" name="min_price" placeholder="Цена от" value="{{ request.GET.min_price }}">
                    <input type="number" name="max_price" placeholder="Цена до" value="{{ request.GET.max_price }}">
                </div>
                <div class='filter-brd'>
                    <label for="brands">Бренды:</label>
                    <select name="brands" id="brands" multiple>
                        {% for brand in brands %}
                        <option value="{{ brand.id }}" {% if brand.id|stringformat:"s" in request.GET.brands %}selected{% endif %}>{{ brand.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class='filter-models'>
                    <label for="models">Модели:</label>
                    <select name="models" id="models" multiple>
                        {% for model in models %}
                        <option value="{{ model.id }}" {% if modelid|stringformat:"s" in request.GET.models %}selected{% endif %}>{{ model.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class='filter-btn'>
                    <button type="submit">Фильтровать</button>
                </div>
            </form>
        </div>
    </div>

{% if flag %}
    <div class="blocks-catalog">
        {% for good in goods %}
        <div class="content-block">
            <a href="{% url 'goods:accessory' good.id %}">
            <div class="photo">
                <img src="{{good.images.url}}" alt="">
            </div>
            <div class="info">
                <h3>{{good.brand}}</h3>
                <p>{{good.name}}</p>
                <p>ОТ {{good.price}} ₸</p>
            </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
<div class="pagination">
    <div class="step-links">
        {% if goods.has_previous %}
            <div class="arrow">
                <a href="?page={{ goods.previous_page_number }}"><img src="{% static 'images/footer/left.svg' %}" alt=""></a>
            </div>
            <div class="previous_page">
                <a href="?page={{ goods.previous_page_number }}">{{ goods.previous_page_number }}</a>
            </div>
        {% endif %}

        <div class="current">
            <a>{{ goods.number }}</a>
        </div>

        {% if goods.has_next %}
            <div class="next_page">
                <a href="?page={{ goods.next_page_number }}">{{ goods.next_page_number }}</a>
            </div>
            <div class="arrow">
                <a href="?page={{ goods.next_page_number }}"><img src="{% static 'images/footer/right.svg' %}" alt=""></a>
            </div>
            {% comment %} <a href="?page={{ goods.paginator.num_pages }}">&raquo;</a> {% endcomment %}
        {% endif %}
        </div>
</div> 
{% else %}
</div>
<a href="https://t.me/highend_hill">
    <div class="not-found">
        <div class="first-part"><h4>В КАТАЛОГЕ НЕТ ИНТЕРЕСУЮЩЕЙ МОДЕЛИ?</h4></div>
        <div class="second-part"><h4>ВЫ ВСЕГДА МОЖЕТЕ ОФОРМИТЬ ИНДВИДУАЛЬНЫЙ ЗАКАЗ, НАПИСАВ НАШЕМУ МЕНЕДЖЕРУ</h4></div>
        <!-- <img src="static/images/header/info.png" alt=""> -->
    </div>
</a>
{% endif %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const selectedBrand = '{{ request.GET.brand }}';
        const selectedSize = '{{ request.GET.sizes }}';
        document.querySelector('select[name="brand"]').value = selectedBrand;
        document.querySelector('select[name="sizes"]').value = selectedSize;
    });
    document.addEventListener("DOMContentLoaded", function() {
        var filterToggles = document.querySelectorAll('.filter-toggle');
    
        filterToggles.forEach(function(toggle) {
            toggle.addEventListener('click', function() {
                var filterArea = this.nextElementSibling;
                this.classList.toggle('active');
                filterArea.classList.toggle('active');
            });
        });
    });
    
</script>

{% endblock main %}

shop/templates/catalog/accessory.html
{% extends "base.html" %}
{% load static %}

{% block main %}
<div class="product-box">
    <div class="images-block">
        <div class="img-shoe">
            <img id="main-image" src="{{ product.images.url }}" alt="">
        </div>
        <div class="other-views">
            {% for img in product.show_images.all %}
            <div class="view" data-image-url="{{ img.img.url }}">
                <img src="{{ img.img.url }}" alt="">
            </div>
            {% endfor %}
        </div>
        
        <div class="info-box">
            <div class="bttns">
                <div>
                    <button onclick="showCategory('category1')">Описание</button>
                </div>
                <div>
                    <button onclick="showCategory('category2')">Доставка</button>
                </div>
                <div>
                    <button onclick="showCategory('category3')">Способы оплаты</button>
                </div>
                <div>
                    <a href="{% url "goods:faq" %}">FAQ</a>
                </div>
            </div>
            <div class="content-info" id="category-content">
                {{ product.description }}
            </div>
            <script>
                const mainImage = document.getElementById('main-image');
                const imageViews = document.querySelectorAll('.view');

                imageViews.forEach((imageView) => {
                    imageView.addEventListener('click', () => {
                        const imageUrl = imageView.getAttribute('data-image-url');
                        mainImage.src = imageUrl;
                    });
                });

                function showCategory(category) {
                    var cont = `{{ product.description }}`;
                    const contentInfo = document.getElementById('category-content');

                    if (category === 'category1') {
                        contentInfo.innerText = cont;
                    } else if (category === 'category2') {
                        contentInfo.innerHTML = `
                            <h5>1.	Сколько занимает доставка из High-End Hill?</h5>
                            Средний срок доставки товара от момента покупки до его прибытия в наш магазин в Алматы составляет 10-20 дней.<br><br>
                            
                            <h5>2.	Что происходит с заказом после оплаты?</h5>
                            После оформления заказа и оплаты, процесс доставки протекает следующим образом:<br><br>
                            1. Заказ передается на закупку. Этот этап занимает от 1 до 3 часов в рабочее время.<br>
                            2. После выкупа мы ожидаем поступления товара на наш склад в Китае. Обычно это занимает от 2 до 3 дней. Однако, в некоторых случаях товар может прибыть уже через 1 день или затянуться до 6 дней.<br>
                            3. После получения товара на складе в Китае, мы отправляем его в Казахстан на следующий день. Срок доставки до нашего магазина в Алматы составляет около 10-15 дней.<br>
                            4. После прибытия товара, наш менеджер свяжется с вами для дальнейших инструкций и уточнения информации о получении заказа.<br><br>
                            
                            <h5>3.	Как работает система доставки в High End Hill?</h5>
                            После оформления заказа и оплаты, у вас будет возможность выбрать удобный способ доставки и указать необходимые данные получателя. Вот варианты доставки, которые мы предлагаем:
                            <br><br>
                            1. Для доставки в Алматы:<br><br>
                            •	Самовывоз из нашего магазина. Если вы находитесь в Алматы и предпочитаете самостоятельно забрать заказ, вы можете приехать в наш пункт выдачи по адресу: проспект Жибек Жолы 76.<br><br>
                            •	Курьерская доставка до вашего адреса. Мы осуществляем доставку вашего заказа курьерской службой прямо до вашей двери.<br><br>
                            
                            2. Для заказов, отправляемых в другие города Казахстана:<br><br>
                            •	Самовывоз из пункта выдачи СДЭК. Вы сможете выбрать удобный для вас пункт выдачи в вашем городе. Как только мы получим ваш заказ в Алматы, мы отправим его в указанный вами пункт выдачи СДЭК.<br><br>
                            •	Доставка курьером СДЭК до вашего дома. Мы организуем доставку вашего заказа курьером прямо к вам по указанному адресу.<br><br>
                            
                            <h5>4.	Как обеспечивается сохранность заказа при доставке?</h5>
                            Наши доставки осуществляются с полной гарантией сохранности вашего заказа. Мы предоставляем полное страхование и обеспечиваем своевременное и качественное исполнение всех заказов.<br><br>
                            
                            <h5>5.	Дополнительная информация</h5>
                            •	Доставка по Казахстану оплачивается дополнительно?<br><br>
                            Да, доставка из Алматы до вашего города или по городу Алматы оплачивается отдельно при получении. Стоимость доставки рассчитывается непосредственно в пункте СДЭК или в приложении доставки курьером.<br><br>
                            •	Если у меня нет СДЭК, могу я оформить доставку КазПочтой или другой компанией?<br><br>
                            Да, вы можете оформить доставку почтой Казахстана или любой другой компанией. Для этого с вами свяжется менеджер и уточнит все детали и ваши предпочтения.<br><br>
                            •	На кого я могу оформить покупку?<br><br>
                            Оформление заказа вы можете делать как на себя, так и на другого человека. Например, если хотите сделать кому-то подарок или занимаетесь перепродажей кроссовок, то вы сразу можете оформить доставку до адреса вашего покупателя.
                            
                        `;
                    } else if (category === 'category3') {
                        contentInfo.innerHTML = `
                        <h5>1.	Какие варианты оплаты доступны?</h5>
                        Вы можете оплатить свой заказ удобным для вас способом: картой казахстанского банка Visa или MasterCard, а также через Kaspi банк или по выставленному счету.<br><br>
                        
                        <h5>2.	Как происходит процесс оформления заказа?</h5>
                        Для оформления заказа вам нужно выбрать интересующий товар и добавить его в корзину. Затем перейдите в корзину, где вы получите уникальный код заказа. С этим кодом вы будете автоматически направлены к нашему менеджеру для уточнения деталей заказа и его оплаты.<br><br>
                        
                        Оплата заказа осуществляется в конце процесса его оформления. После оформления заказа ваша заявка передается менеджеру, который свяжется с вами для проведения оплаты. После успешного получения платежа мы резервируем выбранный вами товар. Пожалуйста, обратите внимание, что цена и наличие товаров могут быть подвержены изменениям до момента оплаты.<br><br>
                        
                        <h5>3.	Нужно ли дополнительно оплачивать налоги, таможенные сборы или доставку?</h5>
                        Нет, не нужно, все налоги, таможенные сборы, доставка и цена за товар уже включены в итоговую стоимость. Отдельно оплачивается только доставка по городу или отправка в другие города.<br>
                        `;
                    }
                }
            </script>
        </div>

    </div>
    <div class="info-price-box">
        <div class="name-box">
            <h1>{{product.brand}} {{product.name}}</h1>
        </div>
        <div class="price-box">
            <h2>ОТ {{product.price}}₸</h2>
        </div>
        <div class="sizes-box">
            {% if product.type|default_if_none:""|force_escape == 'shoes' %}
                <form method="post" id="add-to-cart-form" action="{% url 'goods:add_to_cart' product_id=product.id %}">
            {% else %}
                <form method="post" id="add-to-cart-form" action="{% url 'goods:accessory_add_to_cart' product_id=product.id %}">
            {% endif %}
                {% csrf_token %}
                <input type="hidden" name="size" id="selected-size">

        </div>
        <div class="add_to_buy">
            {% if product.type|default_if_none:""|force_escape == 'shoes' %}
                <form method="post" id="add-to-cart-form" action="{% url 'goods:add_to_cart' product_id=product.id %}">
            {% else %}
                <form method="post" id="add-to-cart-form" action="{% url 'goods:accessory_add_to_cart' product_id=product.id %}">
            {% endif %}
                {% csrf_token %}
                <input type="hidden" name="selected_size" id="selected-size" value="">
                <button type="submit" class="add-to-cart-btn">
                    <span class="btn-text">Добавить в корзину</span>
                    <span class="added-text">Добавлено</span>
                </button>
            </form>
        </div>
        
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const sizeButtons = document.querySelectorAll('.size-btn');
            const addToCartForm = document.getElementById('add-to-cart-form');
            const selectedSizeInput = document.getElementById('selected-size');
            const addBtn = document.querySelector('.add-to-cart-btn');
            const addedText = document.querySelector('.added-text');
        
            sizeButtons.forEach(button => {
                button.addEventListener('click', function() {
                    sizeButtons.forEach(btn => {
                        btn.classList.remove('selected');
                    });
        
                    button.classList.add('selected');
                    const selectedSize = button.getAttribute('data-size');
        
                    selectedSizeInput.setAttribute('value', selectedSize);  // Устанавливаем выбранный размер в скрытое поле
                });
            });
        
            
        });
    </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#add-to-cart-form').submit(function(event) {
                event.preventDefault();

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: $(this).serialize(),  // Отправляем данные из формы
                    success: function(response) {
                        $('.add-to-cart-btn').addClass('added');
                        $('.add-to-cart-btn').attr('disabled', true);
                        $('.added-text').css('display', 'inline');

                        setTimeout(function() {
                            // Можно добавить дополнительную логику после успешного добавления в корзину
                        }, 1000);
                    },
                    error: function(xhr, errmsg, err) {
                        console.log(xhr.status + ": " + xhr.responseText);  // Обработка ошибок
                    }
                });
            });
        });
    </script>
    {% endblock main %}
</div>
{% block content %}
    {% include "includes/others_access.html" %}
    {% include "includes/reverse.html" %}
</div>
{% endblock content %}

shop/templates/catalog/cart.html
{% extends "base.html" %}
{% load static %}

{% block main %}
{% if not cart_items %}
    <div class="name-empty">
        <h2>КОРЗИНА</h2>
    </div>
    <div class='empty_cart'>
        <a href={% url 'goods:shoes' %}>
            <div class='empty'>
                <p>КОРЗИНА ПУСТА</p>
            </div>
            <div class='empty'>
                <p>ПОРА ПЕРЕХОДИТЬ К ПОКУПКАМ</p>
            </div>
            <div class='empty'>
                <img src={% static 'images/faq/arrowDown.svg' %}>
            </div>
        </a>
    </div>
{% endif %}
<div class="cart-box">
    <div class="positions-cart">
        {% if cart_items %}
        <div class="name-empty">
            <h2>КОРЗИНА</h2>
        </div>
        {% endif %}
        <div class="positions">
            <ul>
                {% for item in cart_items %}
                <div class="position">
                    <li>
                        <div class="position-img">
                            <img src="{{item.product.images.url}}">
                        </div>

                        <div class="position-line">
                            <img src="{% static 'images/catalog/yLine.png' %}">
                        </div>

                        <div class="position-info">
                            <div class="brand">
                                <h1>{{item.product.brand}}</h1>
                            </div>
                            <div class="name_size">
                                <h2>{{item.product.name}} {% if item.product.type|stringformat:"s" != 'accessories' %}({{item.size}}){% endif %}</h2>
                            </div>
                            <div class="form-block">

                                <form method="post" action="{% url 'goods:update_cart' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ item.product.id }}">
                                    {% comment %} <input type="number" name="quantity" value="{{ item.quantity }}" min="1"> {% endcomment %}
                                    <div class="centered-number-input">
                                        <button class="decrement"><img width="24" height="24" src="https://img.icons8.com/material-rounded/24/minus.png" alt="minus"/></button>
                                        <input type="number" name="quantity_{{ item.product.id }}" value="{{ item.quantity }}" min="1" class="quantity">
                                        <button class="increment"><img width="24" height="24" src="https://img.icons8.com/android/24/plus.png" alt="plus"/></button>
                                    </div>
                                    
                                    {% comment %} <button type="submit">
                                        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAABIElEQVR4nO3USUoDYRAF4E/BlRo33sBh6wDuRFTwVmKCXiKaIwhKtkoWuYORXMEhgsaFu5aGCrQi3b9DwEUeNHTDq/dq6Com+AMcoIU+XvGCHs6w9xvhVXSRVTzXWCnENVLEd/AUAnc4xDpmUcMGjnEfnAG2QjxLyXwkfo75Eu4i2sF9K1RVim5BfCqh2pmYSbFtpQMdtaUs8yJGbUkyaAUh7/lPxbOygH4Q1owJwzCY8w9Ri+Sex2WwGQa3ZaSvBtZINKgHv/kdg0ai+AIeImY/1aAXS1SFaVxGTKeKnH1a+3acg7LML4L7iKUUg3ocrkF856WfxBAXYsPz96NCW3Lx7YRqP/R8GVcJ57qTknkZdnGKm/jHhzGfZtVAJ5CCdywscWCgJHMnAAAAAElFTkSuQmCC">
                                    </button> {% endcomment %}
                                </form>
                            </div>

                        </div>
                        <div class="delete">
                            <form method="post" action="{% url 'goods:remove_item_from_cart' %}">
                                {% csrf_token %}
                                <input type="hidden" name="product_id" value="{{ item.product.id }}">
                                <button type="submit">
                                    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABkAAAAZCAYAAADE6YVjAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAi0lEQVR4nO3VMQ6AIAyF4f9ib9E7qVdWD6ExOhgTpLTg5FuY6BdCC/AnkAHoIgU49x91khEwA70TELBY9nshWQEvpFKgFJIXsEKKAjlItYAUpNrAvf9XYLrW6DwlMwLbtTZJ1/okzztQ8GXIAtSGcl2kKGRtU3mh0jlQKeQdNFmh6CTLAn3yM/7hLTtHBjH8yNmtagAAAABJRU5ErkJggg==">
                                </button>
                            </form>
                        </div>
                    </li>
                </div>
                {% endfor %}
                <script>
                    document.addEventListener('DOMContentLoaded', function() {
                        document.querySelectorAll('.form-block').forEach(formBlock => {
                            const decrementBtn = formBlock.querySelector('.decrement');
                            const incrementBtn = formBlock.querySelector('.increment');
                            const quantityInput = formBlock.querySelector('.quantity');
                
                            decrementBtn.addEventListener('click', function() {
                                if (parseInt(quantityInput.value) > 1) {
                                    quantityInput.value = parseInt(quantityInput.value) - 1;
                                }
                            });
                
                            incrementBtn.addEventListener('click', function() {
                                quantityInput.value = parseInt(quantityInput.value) + 1;
                            });
                        });
                    });
                </script>
            </ul>
        </div>
    </div>
    {% if cart_items %}
    <div class="results">
        <div class="name">
            <h2>СВЕДЕНИЯ</h2>
        </div>
        <div class="results-content">
            <div class="price-first">
                <div class="text-area">
                    <p>Промежуточный итог</p>
                </div>
                <div class="money">
                    <p>{{ total_price }}₸</p>
                </div>
            </div>

            <div class="price-first">
                <div class="text-area">
                    <p>Предполагаемая стоимость доставки</p>
                </div>
                <div class="money">
                    <p>8000₸</p>
                </div>
            </div>

            <div class="price-first" id="res-bord">
                <div class="text-area">
                    <p>Всего</p>
                </div>
                <div class="money">
                    <p>{{ res_price }}₸</p>
                </div>
            </div>

            <div class="code">
                <div class="btn-code">
                    <button onclick="showCode()" id="getOrderCode">Получить код заказа</button>
                </div>
                
                <div class="code-info" id="code-content"></div>
                
            </div>
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            <script>
                
                function showCode() {
                    // Ваш текущий код
                    console.log(1)
                    var cont = '<a href="https://t.me/highend_hill">{{ code }}</a>';
                    const codeInfo = document.getElementById('code-content');
                    codeInfo.innerHTML = cont;

                    var code = '{{code}}'
                    var cart = {{cart}}

                    $.ajax({
                        type: 'POST',
                        url: '{% url "goods:order" %}',
                        data: {
                            csrfmiddlewaretoken: '{{ csrf_token }}',
                            code: code,
                            cart: cart
                        },
                        success: function(data) {
                            console.log(data);
                        },
                        error: function(xhr, errmsg, err) {
                            console.log(xhr.status + ": " + xhr.responseText);
                        }
                        });
                }
            </script>
            
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

shop/templates/catalog/clothes.html
{% extends "base.html" %}
{% load static %}

{% block main %}
<div class="banners">
    {% for banner in banners %}
    <div class="banner">
        <a href="{{banner.url}}">
            <img src="{{banner.image.url}}" alt="">
        </a>
    </div>
    {% endfor %}
</div>
<div class="list_goods">
    <div class='fltrs'>
        <div class="filter-toggle">ФИЛЬТРЫ</div>
        <div class="filter-area">
            <form method="GET" action="{% url 'goods:clothes' %}">
                <div class='filter-srch'>
                    <input type="text" name="search_query" placeholder="Поиск по названию..." value="{{ request.GET.search_query }}">
                </div>
                <div class='filter-price'>
                    <input type="number" name="min_price" placeholder="Цена от" value="{{ request.GET.min_price }}">
                    <input type="number" name="max_price" placeholder="Цена до" value="{{ request.GET.max_price }}">
                </div>
                <div class='filter-brd'>
                    <label for="brands">Бренды:</label>
                    <select name="brands" id="brands" multiple>
                        {% for brand in brands %}
                        <option value="{{ brand.id }}" {% if brand.id|stringformat:"s" in request.GET.brands %}selected{% endif %}>{{ brand.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class='filter-models'>
                    <label for="models">Модели:</label>
                    <select name="models" id="models" multiple>
                        {% for model in models %}
                        <option value="{{ model.id }}" {% if modelid|stringformat:"s" in request.GET.models %}selected{% endif %}>{{ model.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class='filter-sizes'>
                    <label for="sizes">Размеры:</label>
                    <select name="sizes" id="sizes" multiple>
                        {% for size in sizes %}
                        <option value="{{ size.id }}" {% if size.id|stringformat:"s" in request.GET.sizes %}selected{% endif %}>{{ size.size }}</option>
                        {% endfor %}
                    </select>
                </div>
            
                <div class='filter-btn'>
                    <button type="submit">Фильтровать</button>
                </div>
            </form>
        </div>
    </div>

{% if flag %}
    <div class="blocks-catalog">
        {% for good in goods %}
        <div class="content-block">
            <a href="{% url 'goods:cloth' good.id %}">
            <div class="photo">
                <img src="{{good.images.url}}" alt="">
            </div>
            <div class="info">
                <h3>{{good.brand}}</h3>
                <p>{{good.name}}</p>
                <p>ОТ {{good.price}} ₸</p>
            </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
<div class="pagination">
    <div class="step-links">
        {% if goods.has_previous %}
            <div class="arrow">
                <a href="?page={{ goods.previous_page_number }}"><img src="{% static 'images/footer/left.svg' %}" alt=""></a>
            </div>
            <div class="previous_page">
                <a href="?page={{ goods.previous_page_number }}">{{ goods.previous_page_number }}</a>
            </div>
        {% endif %}

        <div class="current">
            <a>{{ goods.number }}</a>
        </div>

        {% if goods.has_next %}
            <div class="next_page">
                <a href="?page={{ goods.next_page_number }}">{{ goods.next_page_number }}</a>
            </div>
            <div class="arrow">
                <a href="?page={{ goods.next_page_number }}"><img src="{% static 'images/footer/right.svg' %}" alt=""></a>
            </div>
            {% comment %} <a href="?page={{ goods.paginator.num_pages }}">&raquo;</a> {% endcomment %}
        {% endif %}
        </div>
</div> 
{% else %}
</div>
<a href="https://t.me/highend_hill">
    <div class="not-found">
        <div class="first-part"><h4>В КАТАЛОГЕ НЕТ ИНТЕРЕСУЮЩЕЙ МОДЕЛИ?</h4></div>
        <div class="second-part"><h4>ВЫ ВСЕГДА МОЖЕТЕ ОФОРМИТЬ ИНДВИДУАЛЬНЫЙ ЗАКАЗ, НАПИСАВ НАШЕМУ МЕНЕДЖЕРУ</h4></div>
        <!-- <img src="static/images/header/info.png" alt=""> -->
    </div>
</a>
{% endif %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const selectedBrand = '{{ request.GET.brand }}';
        const selectedSize = '{{ request.GET.sizes }}';
        document.querySelector('select[name="brand"]').value = selectedBrand;
        document.querySelector('select[name="sizes"]').value = selectedSize;
    });
    document.addEventListener("DOMContentLoaded", function() {
        var filterToggles = document.querySelectorAll('.filter-toggle');
    
        filterToggles.forEach(function(toggle) {
            toggle.addEventListener('click', function() {
                var filterArea = this.nextElementSibling;
                this.classList.toggle('active');
                filterArea.classList.toggle('active');
            });
        });
    });
    
</script>

{% endblock main %}