shop/goods/urls.py
from django.urls import path

from .views import shoes, index, shoescart, view_cart, update_cart, remove_item_from_cart, display_info, order, popular, newest, delivery, sale, clothes, clothcart, money, money_back, accessories, accessory

app_name = 'goods'

urlpatterns = [
    path('', index, name='index'),

    path('shoes/', shoes, name='shoes'),
    path('clothes/', clothes, name='clothes'),
    path('accessories/', accessories, name='accessories'),

    path('shoes/<int:product_id>/', shoescart, name="shoe"),
    path('clothes/<int:product_id>/', clothcart, name="cloth"),
    path('accessories/<int:product_id>/', accessory, name='accessory'),

    path('shoes/add_to_cart/<int:product_id>/', shoescart, name='add_to_cart'),
    path('clothes/add_to_cart/<int:product_id>/', clothcart, name='clothes_add_to_cart'),
    path('accessories/add_to_cart/<int:product_id>/', accessory, name='accessory_add_to_cart'),

    path('view_cart/', view_cart, name='view_cart'),
    path('update_cart/', update_cart, name='update_cart'),
    path('remove_item_from_cart/', remove_item_from_cart, name='remove_item_from_cart'),
    path('order/', order, name='order'),

    path('popular/', popular, name='popular'),
    path('new/', newest, name='new'),
    path('sale/', sale, name='sale'),

    path('faq/', display_info, name='faq'),
    path('delivery/', delivery, name='delivery'),
    path('payment/', money, name='payment'),
    path('return-info/', money_back, name='return')

]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from shop import settings

urlpatterns = [
    path('', include('goods.urls', namespace='goods')),
    path('admin/', admin.site.urls),
]



if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/templates/includes/others.html
<div class="inspiration">
    <a href="#"><h2>ДРУГИЕ МОДЕЛИ</h2></a>
    <div class="blocks">
        {% for good in look_at %}
        <a href="{% url 'goods:shoe' good.id %}">
        <div class="content-block">
            <div class="photo">
                <img src="{{good.images.url}}" alt="">
            </div>
            <div class="info">
                <h3>{{good.name}}</h3>
                <p>ОТ {{good.price}}₸</p>
            </div>
        </div>
        </a>
        {% endfor %}
    </div>
</div>

shop/templates/includes/others_access.html
<div class="inspiration">
    <a href="#"><h2>ДРУГИЕ МОДЕЛИ</h2></a>
    <div class="blocks">
        {% for good in look_at %}
        <div class="content-block">
            <a href="{% url 'goods:accessory' good.id %}">
            <div class="photo">
                <img src="{{good.images.url}}" alt="">
            </div>
            <div class="info">
                <h3>{{good.brand}}</h3>
                <h3>{{good.name}}</h3>
                <p>ОТ {{good.price}}₸</p>
            </div>
        </a>
        </div>
        {% endfor %}
    </div>
</div>

shop/templates/includes/others_clothes.html
<div class="inspiration">
    <a href="#"><h2>ДРУГИЕ МОДЕЛИ</h2></a>
    <div class="blocks">
        {% for good in look_at %}
        <div class="content-block">
            <a href="{% url 'goods:cloth' good.id %}">
            <div class="photo">
                <img src="{{good.images.url}}" alt="">
            </div>
            <div class="info">
                <h3>{{good.brand}}</h3>
                <h3>{{good.name}}</h3>
                <p>ОТ {{good.price}}₸</p>
            </div>
        </a>
        </div>
        {% endfor %}
    </div>
</div>

shop/templates/includes/reverse.html
{% load static %}
<div class="reverse">
    {% if product.type|default_if_none:""|force_escape == 'shoes' %}
        <a href="{% url "goods:shoes" %}">
    {% elif product.type|default_if_none:""|force_escape == 'clothes' %}
        <a href="{% url "goods:clothes" %}">
    {% else %}
        <a href="{% url "goods:accessories" %}">
    {% endif %}
        <div class="reverse-btn">
            <div class="txt-reverse">
                <p>ПРОДОЛЖИТЬ ПОКУПКИ</p>
            </div>
            <div class="svg-reverse">
                <img src="{% static 'images/catalog/arrow.svg' %}" alt="">
            </div>
        </div>
    </a>
</div>