shop/goods/urls.py
from django.urls import path

from .views import shoes, index, shoescart, view_cart, update_cart, remove_item_from_cart, display_info, order, popular, newest, delivery, sale, clothes, clothcart, money, money_back, accessories, accessory

app_name = 'goods'

urlpatterns = [
    path('', index, name='index'),

    path('shoes/', shoes, name='shoes'),
    path('clothes/', clothes, name='clothes'),
    path('accessories/', accessories, name='accessories'),

    path('shoes/<int:product_id>/', shoescart, name="shoe"),
    path('clothes/<int:product_id>/', clothcart, name="cloth"),
    path('accessories/<int:product_id>/', accessory, name='accessory'),

    path('shoes/add_to_cart/<int:product_id>/', shoescart, name='add_to_cart'),
    path('clothes/add_to_cart/<int:product_id>/', clothcart, name='clothes_add_to_cart'),
    path('accessories/add_to_cart/<int:product_id>/', accessory, name='accessory_add_to_cart'),

    path('view_cart/', view_cart, name='view_cart'),
    path('update_cart/', update_cart, name='update_cart'),
    path('remove_item_from_cart/', remove_item_from_cart, name='remove_item_from_cart'),
    path('order/', order, name='order'),

    path('popular/', popular, name='popular'),
    path('new/', newest, name='new'),
    path('sale/', sale, name='sale'),

    path('faq/', display_info, name='faq'),
    path('delivery/', delivery, name='delivery'),
    path('payment/', money, name='payment'),
    path('return-info/', money_back, name='return')

]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from shop import settings

urlpatterns = [
    path('', include('goods.urls', namespace='goods')),
    path('admin/', admin.site.urls),
]



if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block main %}
    <div class="banner-ind">
        <a href ="{{banner.url}}">
            <div class="banner-f">
                <img src="{{banner.image.url}}" alt="">
            </div>
        </a>
    </div>
    <div class="banner-ind-2">
        <a href ="{{banner_mobile.url}}">
            <div class="banner-f">
                <img src="{{banner_mobile.image.url}}" alt="">
            </div>
        </a>
    </div>
    <div class="popular">
        <div class="text-area">
            <div class="most">
                <a href="{% url "goods:popular" %}"><h2>MOST POPULAR</h2></a>
            </div>
            <div class="most">
                <a href="{% url "goods:popular" %}"><h2>SEE ALL</h2></a>
            </div>
        </div>
        <div class="blocks">
            {% for good in liked %}
            <div class="content-block">
                <a href="{% url 'goods:shoe' good.id %}">
                <div class="photo">
                    <img src="{{good.images.url}}" alt="">
                </div>
                <div class="info">
                    <h3>{{good.brand}}</h3>
                    <p>{{good.name}}</p>
                    <p>ОТ {{good.price}}₸</p>
                </div>
            </a>
            </div>
            {% endfor %}
        </div>
    </div>
            
    <div class="new-models">
        <div class="text-area">
            <div class="most">
                <a href="{% url "goods:new" %}"><h2>NEW MODELS</h2></a>
            </div>
            <div class="most">
                <a href="{% url "goods:new" %}"><h2>SEE ALL</h2></a>
            </div>
        </div>
        <div class="blocks">
            {% for good in goods %}
            <div class="content-block">
                <a href="{% url 'goods:shoe' good.id %}">
                <div class="photo">
                    <img src="{{good.images.url}}" alt="">
                </div>
                <div class="info">
                    <h3>{{good.brand}}</h3>
                    <p>{{good.name}}</p>
                    <p>ОТ {{good.price}}₸</p>
                </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    <a href="https://t.me/highend_hill">
    <div class="not-found">
        <div class="first-part"><h4>В КАТАЛОГЕ НЕТ ИНТЕРЕСУЮЩЕЙ МОДЕЛИ?</h4></div>
        <div class="second-part"><h4>ВЫ ВСЕГДА МОЖЕТЕ ОФОРМИТЬ ИНДВИДУАЛЬНЫЙ ЗАКАЗ, НАПИСАВ НАШЕМУ МЕНЕДЖЕРУ</h4></div>
        <!-- <img src="static/images/header/info.png" alt=""> -->
    </div>
    </a>
{% endblock main %}